### ISSUE TITLE
Automated configuration generation

### ISSUE THREAD

**Issue by Spartee** [CrayLabs/SmartSim#38]
# Description
Generate a ``config.toml`` for SmartSim as a part of the pip installation process. 

# Justification
Users currently have to setup a configuration file manually as a part of the installation process. This could be automated with a brief python script that detects existing installations and writes a ``config.toml`` based on those installations.

# Implementation Strategy
Write a brief python script that detects existing installations and writes a ``config.toml`` based on those installations. Additionally, find a sensible default method for the configuration and provide that in the case where users follow a quick start installation. 

## TODO
 - [x] Write script to detect Redis, RedisAI, and RedisIP installations
 - [x] generate config.toml based on installations
 - [x] write to ``$HOME`` if possible, otherwise write to install directory and provide a line to add ``SMARTSIM_HOME`` to profile
 - [x] (Optional) provide a base configuration that lies within the installation directory and is automatically used if the user does not provide their own.
