### ISSUE TITLE
Add support for building on Apple Silicon

### ISSUE THREAD

**Issue by ashao** [CrayLabs/SmartSim#454]
# Description
Apple Silicon (M1, M2, and M3) are `arm64` and are increasingly being used as a development platform. Currently SmartSim does not build on these platforms because libtorch and libtensorflow, used to build the RedisAI backends, are only available precompiled for x86_64. In order to add support we need to come up with a solution to compile these libraries ourselves and potentially host the binaries as well.

# Justification
Adding support for Apple Silicon will allow developers and users of SmartSim to prototype and test their code locally. This can reduce the barrier to entry and also reduce the iteration time for debugging and development.

# Implementation Strategy
The implementation of this strategy is two-phased to reduce risks. Part I creates a system by which we can build libtorch and libtensorflow on existing amd64 architecture. Part II then tests and deploys this for ARM64

## Part I [Replicate RedisAI build using custom-built libraries (instead of precompiled)]
Create a new repository that captures the processes needed to build libtensorflow and libtorch. The compiled versions of these libraries should then be used in the RedisAI build step instead. This step will also need some research to understand whether distributing our own compiled binaries is within the source code rights and also build out some (potentially Github-based infrastructure) to host these libraries.

## Part II [Modify Part I to target arm64]
This step is in theory, a simple modification to Part I, to build on arm64 instead of amd64 but is a separate step as it may carry its own risks.

# Acceptance criteria
- [ ] Receive approval/get clarity to distribute precompiled libraries
- [ ] All tests pass using precompiled libraries on amd64
- [ ] All tests pass using precompiled libaries on arm64
- [ ] Add testing on Apple Silicon to SmartSim Github Actions
